### ISSUE TITLE
TST: Test against Python 3.11

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13224]
https://github.com/actions/setup-python is now providing Python 3.11, according to their README. For example:

```yaml
- uses: actions/setup-python@v3
  with:
    python-version: '3.11.0-alpha.1'
```

```yaml
- uses: actions/setup-python@v3
  with:
    python-version: '3.11-dev'
```

Maybe it is too early yet but eventually we would want to start testing `astropy` with Python 3.11.

https://peps.python.org/pep-0664/ (This release schedule says that beta 1 is supposed to come out today, 2022-05-06)

https://docs.python.org/3.11/whatsnew/3.11.html
