### ISSUE TITLE
Custom directive to skip RTD or not worth it?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14152]
RTD still does not automatically skip with `[ci skip]` etc directive automatically, but they have provided a way for us to implement such a thing in https://github.com/readthedocs/readthedocs.org/pull/9649 .

Example downstream implementation is here: https://github.com/spacetelescope/jdaviz/blob/17fe3a8625c1e43daaafd7f666de1e9fdedd9dec/.readthedocs.yaml#L13

```yaml
build:
# ...
  jobs:
    post_checkout:
      # Use `git log` to check if the latest commit contains "skip rtd" or "rtd skip",
      # in that case exit the command with 183 to skip the build
      - MSG=`git --no-pager log --pretty="tformat:%s -- %b" -1`; case $MSG in *"skip rtd"*|*"rtd skip"*) exit 183;; *);; esac
```

Are we interested enough in this feature to adopt such a solution?
