### ISSUE TITLE
Add a citation.cff file

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#14755]
### What is the problem this feature will solve?

Helps with citations.

### Describe the desired outcome

We add a CITATION.cff file.

### Additional context

https://citation-file-format.github.io

**Comment by pllim** [comment]
I vaguely remember we put citation in https://github.com/astropy/astropy/blob/main/astropy/CITATION so we can somehow programmatically show it from within the package or something. Maybe @adrn can clarify.

**Comment by adrn** [comment]
We have some descriptive text along with multiple citations in the current CITATION file - it's useful to have the bibtex strings available for copy and paste in there. I think there's an argument to add a CITATION.cff file *in addition* to the CITATION file. @nstarman do you understand the markup enough to generate a CFF file?

**Comment by nstarman** [comment]
I'm looking at the spec and I don't see anything about multiple papers. But making a cff isn't too hard...

[CITATION.txt](https://github.com/astropy/astropy/files/11425011/CITATION.txt)

There are some automatic tools out there which would be good to use to get the full author list. Just to get a feel for cff I used [cffinit](https://citation-file-format.github.io/cff-initializer-javascript/#/)

**Comment by adrn** [comment]
Minor observations from looking at the auto-generated file: I looks like it didn't like the "." in "v5.0" in the title, and it cuts the author list pretty short...

**Comment by nstarman** [comment]
> Minor observations from looking at the auto-generated file: I looks like it didn't like the "." in "v5.0" in the title

"v5" is good enough. 

> and it cuts the author list pretty short...

That was me. It takes a bit of time to add ORCID and institution info. I just didn't go very far in my testing. I tried using some automated tools but I had trouble getting them to scrape ORCID and institution info, so I just made the example file by hand.

**Comment by olebole** [comment]
@adrn
> And is it possible to have multiple papers / entries in one CFF file? (we ask people to cite all 3 astropy papers)

I am just in the process to create a [CITATION.cff](https://github.com/olebole/iraf/blob/citation-cff/CITATION.cff) for IRAF (https://github.com/iraf-community/iraf/pull/306), and I may be able to help here a bit, because I basically had the same issue there (two papers can be cited). I asked the question on their issue tracker (https://github.com/citation-file-format/citation-file-format/issues/436), and the possible solution is to have the primary reference in **preferred-citation** and all others as references. Citing from the IRAF CFF:

```yaml
preferred-citation:
  authors:
    - family-names: Tody
      given-names: Doug
  title: "The IRAF Data Reduction and Analysis System"
  [… more info about the primary paper]

references:
  - authors:
      - family-names: Tody
        given-names: Doug
    title: "IRAF in the Nineties"
    [… more info about the first additional paper]

  […more additional papers]
```

The disadvantage here is that there is clearly one paper the primary one; so a "please cite all" is a bit complicated.

I finally decided to create the file by hand, since the generation tool was not very smart, and go great help from one of the authors.  

Since I did that just for IRAF, I would volunteer to to create a PR for this on astropy while my impressions are still fresh :-) Based on @nstarman's  file above.
Is there an author's list with ORCIDs somewhere that could be transformed?

Since this file would need an update for each new version (DOI, authors list adjustments), it should be included in the "prepare a new version" workflow.
