### ISSUE TITLE
Revive milestone check in CI?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#16041]
Back in the Travis CI days, we used to have a milestone check job that blocks merge unless a PR is milestoned. When we switched to GitHub Actions, milestone events were no longer triggered from PR (don't ask me why) and this check was dumbed down to a checkbox in a bot comment that maintainers sometimes miss.

Now in https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request , I see that `milestoned` and `demilestoned` are explicitly listed. Maybe they work now? There is need to investigate whether we could implement the old milestone check as a CI job, using GitHub Actions.

Related issue:

* https://github.com/astropy/astropy/issues/14897

**Comment by neutrinoceros** [comment]
I can work on this as soon as tomorrow and either open a PR or report back with anything I find is *not* working !

**Comment by pllim** [comment]
Thanks! Here are my ideas:

* Implement this check as a new workflow on your fork with Action enabled there.
* This workflow should only listens to `pull_request`, `milestoned`, `demilestoned`.
* When there is no milestone, it fails.

Fancier checks can go in later. We just need to know if those events actually work in the first pass.

**Comment by pllim** [comment]
No much fancy code needs to happen. I think we can use `github-script` directly like here:

https://github.com/astropy/astropy/blob/caf9a1ad01debeda56092241ab7e5586de978e4a/.github/workflows/open_actions.yml#L21

But you might need to dig into octokit nodejs API to grab the milestone from PR and then issue pass/fail status.

**Comment by neutrinoceros** [comment]
I spent an hour in this and couldn't find anything in the reference docs that I could use to query the current milestone on a pull request (admittedly, I'm out of my depth here so I may just be missing something that someone with more experience with octokit would find easily ?).

Here's what I could understand from my experiments on my fork though:
- individual `milestoned` and `demilestoned` events work as expected
- when switching a milestone from the web interface, it seems that, contrary to my intuition, the order in which the sequence is played behind the curtain is `[milestoned, demilestoned]` (maybe they're really unrelated and happen asynchronously, but that's not relevant). This means that we cannot simply fail the workflow on `demilestoned` as I initially thought.
- it is not sufficient to listen to `milestoned` and `demilestoned` events: the workflow also need to be triggered on `opened`

So I think the basic structure of the workflow would look something like the following

```yaml
name: Check milestone

on:
  pull_request_target:
    types:
      - opened
      - milestoned
      - demilestoned

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Validate Milestone
      if: github.event.action == 'milestoned'
      run: exit 0

    - name: Check Milestone
      if: github.event.action == 'opened' | github.event.action == 'demilestoned'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          ...
```

Obviously, I've left out the most important part: the actual check script !
However, in hindsight, this seems too far from my current skillset to be worth what my time costs, so I'll un-assign myself. Sorry I misjudged the difficulty of this task !
