### ISSUE TITLE
TST: Auto cancel on optional jobs should be more robust

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#17183]
### Problem

In #17115 , I made the `if` conditions stricter so irrelevant "labeled" events will not trigger other optional jobs that are also driven by labels. An undesirable side effect is that they are also set to auto-cancel when duplicate job is detected. So such workflow becomes problematic:

1. Someone opens PR.
2. Maintainer applies "Extra CI" label to trigger cron jobs. They would run as expected.
3. But then maintainer also applies "Build all wheels" label to trigger wheel jobs. Now wheel jobs would run *but* the cron jobs detects duplicate GitHub Actions context and would cancel and they will not run again because the latest label is irrelevant, so as a result, now the cron jobs would show as cancelled. This will not block merge but also will not give the maintainer cron job runs as requested.

### Possible solutions

1. Live with it. Maintainer has to apply a label, wait for that set of jobs to finish running before applying another one to kick off a different set of jobs.
2. Revert #17115 (but then the problem it was trying to fix will come back).
3. ❌ Investigate if we can fine tune `group` condition to fix this problem: https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs (this one will need the investigator to play around with different possible combos on their own fork first)

**Comment by pllim** [comment]
There are 2 different routes I have to play with.

### Option 1

Keep it workflow level but tighten the cancel condition; example:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'pull_request' || (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'Extra CI')) || (github.event.action == 'labeled' && github.event.label.name == 'Extra CI') }}
```

### Option 2

Keep it job level. This is cleaner but I am not sure if a job that is conditioned to skip is counted as "triggered" or not. From https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#example-concurrency-groups

```yaml
jobs:
  job-1:
    runs-on: ubuntu-latest
    concurrency:
      group: staging_environment
      cancel-in-progress: true
```
