### ISSUE TITLE
ASDF interface for Table

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3733]
We should add a reader/writer for ASDF for tables (which can have pyasdf as an optional dependency for now). But first, a philosophical question: should we store the table by rows or by columns? For the former, we'd use a structured array, while for the latter, we'd use a dictionary of Numpy arrays. The latter would be faster because that is how Table is stored internally, and it also allows us to store each column's metadata alongside the column it applies to. So the difference would be:

``` python
t = Table(...)

# Row-first:

tree1 = {'data':np.array(t)}

# also store the column metadata in another structure

ff = AsdfFile(tree1)
ff.write_to("example1.asdf")

# Column-first:

tree2 = {}
for colname in t.columns:
    tree2[colname] = {}
    tree2[colname]['data'] = t.columns[colname]
    tree2[colname]['unit'] = str(t.columns[colname].unit)
    tree2[colname]['description'] = str(t.columns[colname].description)

ff = AsdfFile(tree2)
ff.write_to("example2.asdf")
```

The latter seems more elegant to me and is a bit faster in real-life tests, and I like the inclusion of the column meta-data alongside each array. This looks like:

```
--- !core/asdf
col1:
  data: !core/ndarray
    source: 2
    datatype: [ascii, 25]
    byteorder: big
    shape: [4455]
  description: GLIMPSE source name
  unit: '---'
col10:
  data: !core/ndarray
    source: 9
    datatype: [ascii, 1]
    byteorder: big
    shape: [4455]
  description: "Variablity flag (2) \n    Y = The magnitudes for the two epochs differ
    by at least 0.3 mag at either \n        (or both) 4.5 microns or 8.0 microns.
    \n    N = Not variable."
  unit: '---'
col2:
  data: !core/ndarray
    source: 8
    datatype: float32
    byteorder: little
    shape: [4455]
  description: "Galatic longitude (1) These coordinates are set to the average position
    of the source at \n          4.5 and at 8.0 microns, as in Table 2."
  unit: deg
```

cc @taldcroft @embray @taldcroft
